# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f1edd804856c436439a7752cda49b73606cbf24e5183ccae8bd07fa57892e37c1c8e11a483f857024f655f301651910623a6ed41bda51354acb753216c58bb

test:
  secret_key_base: 32f5ed7f1096a1075f46e91063b069af0d0c5b121b2b3323ce7e8860761b744847497f0162159b996d9229c75319f2650b508ec1589a53e481b4b33b8254aaef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
